apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-api
  namespace: observability-demo
spec:
  template:
    metadata:
      labels:
        version: v2
    spec:
      containers:
        - name: orders-api
          image: orders-api:v2
          imagePullPolicy: IfNotPresent
          env:
            - name: OTEL_SERVICE_NAME
              value: orders-api
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector:4317
            - name: APP_VERSION
              value: v2
