apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-api
  namespace: observability-demo
spec:
  template:
    spec:
      containers:
        - name: orders-api
          env:
            - name: OTEL_SERVICE_NAME
              value: orders-api
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector-wrong:4317
